"""set import recipe delete behavior

Revision ID: d233b81fb1fc
Revises: b9ea7919c36f
Create Date: 2026-09-04 21:12:23.948562

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd233b81fb1fc'
down_revision: str | Sequence[str] | None = 'b9ea7919c36f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("recipe_imports_recipe_id_fkey"),
        "recipe_imports",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("recipe_imports_recipe_id_fkey"),
        "recipe_imports",
        "recipes",
        ["recipe_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("recipe_imports_recipe_id_fkey"),
        "recipe_imports",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("recipe_imports_recipe_id_fkey"),
        "recipe_imports",
        "recipes",
        ["recipe_id"],
        ["id"],
    )
    # ### end Alembic commands ###
